//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.13 at 06:19:14 AM CET 
//


package com.openfms.model.core.media.dcp.interop.cpl;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MarkerAssetType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MarkerAssetType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.digicine.com/PROTO-ASDCP-CPL-20040511#}GenericAssetType">
 *       &lt;sequence>
 *         &lt;element name="MarkerList">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Marker" type="{http://www.digicine.com/PROTO-ASDCP-CPL-20040511#}MarkerType" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MarkerAssetType", namespace = "http://www.digicine.com/PROTO-ASDCP-CPL-20040511#", propOrder = {
    "markerList"
})
public class MarkerAssetType
    extends GenericAssetType
{

    @XmlElement(name = "MarkerList", required = true)
    protected MarkerAssetType.MarkerList markerList;

    /**
     * Gets the value of the markerList property.
     * 
     * @return
     *     possible object is
     *     {@link MarkerAssetType.MarkerList }
     *     
     */
    public MarkerAssetType.MarkerList getMarkerList() {
        return markerList;
    }

    /**
     * Sets the value of the markerList property.
     * 
     * @param value
     *     allowed object is
     *     {@link MarkerAssetType.MarkerList }
     *     
     */
    public void setMarkerList(MarkerAssetType.MarkerList value) {
        this.markerList = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Marker" type="{http://www.digicine.com/PROTO-ASDCP-CPL-20040511#}MarkerType" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "marker"
    })
    public static class MarkerList {

        @XmlElement(name = "Marker", namespace = "http://www.digicine.com/PROTO-ASDCP-CPL-20040511#")
        protected List<MarkerType> marker;

        /**
         * Gets the value of the marker property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the marker property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getMarker().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link MarkerType }
         * 
         * 
         */
        public List<MarkerType> getMarker() {
            if (marker == null) {
                marker = new ArrayList<MarkerType>();
            }
            return this.marker;
        }

    }

}
