//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.13 at 06:20:39 AM CET 
//


package com.openfms.model.core.media.dcp.subtitles;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SubtitleID" type="{}UUIDType"/>
 *         &lt;element name="MovieTitle" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ReelNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Language" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element ref="{}LoadFont" minOccurs="0"/>
 *         &lt;element ref="{}Font" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}Subtitle" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="Version" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="1.0"/>
 *             &lt;enumeration value="1.1"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "subtitleID",
    "movieTitle",
    "reelNumber",
    "language",
    "loadFont",
    "font",
    "subtitle"
})
@XmlRootElement(name = "DCSubtitle")
public class DCSubtitle {

    @XmlElement(name = "SubtitleID", required = true)
    protected String subtitleID;
    @XmlElement(name = "MovieTitle", required = true)
    protected String movieTitle;
    @XmlElement(name = "ReelNumber", required = true)
    protected String reelNumber;
    @XmlElement(name = "Language", required = true)
    protected String language;
    @XmlElement(name = "LoadFont")
    protected LoadFont loadFont;
    @XmlElement(name = "Font")
    protected List<Font> font;
    @XmlElement(name = "Subtitle")
    protected List<Subtitle> subtitle;
    @XmlAttribute(name = "Version", required = true)
    protected String version;

    /**
     * Gets the value of the subtitleID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubtitleID() {
        return subtitleID;
    }

    /**
     * Sets the value of the subtitleID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubtitleID(String value) {
        this.subtitleID = value;
    }

    /**
     * Gets the value of the movieTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMovieTitle() {
        return movieTitle;
    }

    /**
     * Sets the value of the movieTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMovieTitle(String value) {
        this.movieTitle = value;
    }

    /**
     * Gets the value of the reelNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReelNumber() {
        return reelNumber;
    }

    /**
     * Sets the value of the reelNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReelNumber(String value) {
        this.reelNumber = value;
    }

    /**
     * Gets the value of the language property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLanguage() {
        return language;
    }

    /**
     * Sets the value of the language property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLanguage(String value) {
        this.language = value;
    }

    /**
     * Gets the value of the loadFont property.
     * 
     * @return
     *     possible object is
     *     {@link LoadFont }
     *     
     */
    public LoadFont getLoadFont() {
        return loadFont;
    }

    /**
     * Sets the value of the loadFont property.
     * 
     * @param value
     *     allowed object is
     *     {@link LoadFont }
     *     
     */
    public void setLoadFont(LoadFont value) {
        this.loadFont = value;
    }

    /**
     * Gets the value of the font property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the font property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFont().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Font }
     * 
     * 
     */
    public List<Font> getFont() {
        if (font == null) {
            font = new ArrayList<Font>();
        }
        return this.font;
    }

    /**
     * Gets the value of the subtitle property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the subtitle property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSubtitle().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Subtitle }
     * 
     * 
     */
    public List<Subtitle> getSubtitle() {
        if (subtitle == null) {
            subtitle = new ArrayList<Subtitle>();
        }
        return this.subtitle;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

}
