//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.13 at 06:20:39 AM CET 
//


package com.openfms.model.core.media.dcp.subtitles;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element ref="{}Font" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}Text" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}Image"/>
 *       &lt;/choice>
 *       &lt;attribute name="SpotNumber" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="TimeIn" use="required" type="{}timeType" />
 *       &lt;attribute name="TimeOut" use="required" type="{}timeType" />
 *       &lt;attribute name="FadeUpTime" type="{}fadeTimeType" />
 *       &lt;attribute name="FadeDownTime" type="{}fadeTimeType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "fontOrTextOrImage"
})
@XmlRootElement(name = "Subtitle")
public class Subtitle {

    @XmlElements({
        @XmlElement(name = "Font", type = Font.class),
        @XmlElement(name = "Text", type = Text.class),
        @XmlElement(name = "Image", type = Image.class)
    })
    protected List<Object> fontOrTextOrImage;
    @XmlAttribute(name = "SpotNumber", required = true)
    protected String spotNumber;
    @XmlAttribute(name = "TimeIn", required = true)
    protected String timeIn;
    @XmlAttribute(name = "TimeOut", required = true)
    protected String timeOut;
    @XmlAttribute(name = "FadeUpTime")
    protected String fadeUpTime;
    @XmlAttribute(name = "FadeDownTime")
    protected String fadeDownTime;

    /**
     * Gets the value of the fontOrTextOrImage property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the fontOrTextOrImage property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFontOrTextOrImage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Font }
     * {@link Text }
     * {@link Image }
     * 
     * 
     */
    public List<Object> getFontOrTextOrImage() {
        if (fontOrTextOrImage == null) {
            fontOrTextOrImage = new ArrayList<Object>();
        }
        return this.fontOrTextOrImage;
    }

    /**
     * Gets the value of the spotNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpotNumber() {
        return spotNumber;
    }

    /**
     * Sets the value of the spotNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpotNumber(String value) {
        this.spotNumber = value;
    }

    /**
     * Gets the value of the timeIn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTimeIn() {
        return timeIn;
    }

    /**
     * Sets the value of the timeIn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTimeIn(String value) {
        this.timeIn = value;
    }

    /**
     * Gets the value of the timeOut property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTimeOut() {
        return timeOut;
    }

    /**
     * Sets the value of the timeOut property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTimeOut(String value) {
        this.timeOut = value;
    }

    /**
     * Gets the value of the fadeUpTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFadeUpTime() {
        return fadeUpTime;
    }

    /**
     * Sets the value of the fadeUpTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFadeUpTime(String value) {
        this.fadeUpTime = value;
    }

    /**
     * Gets the value of the fadeDownTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFadeDownTime() {
        return fadeDownTime;
    }

    /**
     * Sets the value of the fadeDownTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFadeDownTime(String value) {
        this.fadeDownTime = value;
    }

}
