//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.13 at 06:20:39 AM CET 
//


package com.openfms.model.core.media.dcp.subtitles;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlMixed;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice minOccurs="0">
 *         &lt;element ref="{}Font" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}Ruby" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}Space" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}HGroup" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}Rotate" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/choice>
 *       &lt;attribute name="Direction">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="horizontal"/>
 *             &lt;enumeration value="vertical"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="HAlign" type="{}hAlignType" />
 *       &lt;attribute name="HPosition" type="{}positionType" />
 *       &lt;attribute name="VAlign" use="required" type="{}vAlignType" />
 *       &lt;attribute name="VPosition" use="required" type="{}positionType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "content"
})
@XmlRootElement(name = "Text")
public class Text {

    @XmlElementRefs({
        @XmlElementRef(name = "Ruby", type = Ruby.class, required = false),
        @XmlElementRef(name = "Rotate", type = Rotate.class, required = false),
        @XmlElementRef(name = "HGroup", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Space", type = Space.class, required = false),
        @XmlElementRef(name = "Font", type = Font.class, required = false)
    })
    @XmlMixed
    protected List<Object> content;
    @XmlAttribute(name = "Direction")
    protected String direction;
    @XmlAttribute(name = "HAlign")
    protected HAlignType hAlign;
    @XmlAttribute(name = "HPosition")
    protected BigDecimal hPosition;
    @XmlAttribute(name = "VAlign", required = true)
    protected VAlignType vAlign;
    @XmlAttribute(name = "VPosition", required = true)
    protected BigDecimal vPosition;

    /**
     * Gets the value of the content property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the content property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link Ruby }
     * {@link Rotate }
     * {@link String }
     * {@link Font }
     * {@link Space }
     * 
     * 
     */
    public List<Object> getContent() {
        if (content == null) {
            content = new ArrayList<Object>();
        }
        return this.content;
    }

    /**
     * Gets the value of the direction property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDirection() {
        return direction;
    }

    /**
     * Sets the value of the direction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDirection(String value) {
        this.direction = value;
    }

    /**
     * Gets the value of the hAlign property.
     * 
     * @return
     *     possible object is
     *     {@link HAlignType }
     *     
     */
    public HAlignType getHAlign() {
        return hAlign;
    }

    /**
     * Sets the value of the hAlign property.
     * 
     * @param value
     *     allowed object is
     *     {@link HAlignType }
     *     
     */
    public void setHAlign(HAlignType value) {
        this.hAlign = value;
    }

    /**
     * Gets the value of the hPosition property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getHPosition() {
        return hPosition;
    }

    /**
     * Sets the value of the hPosition property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setHPosition(BigDecimal value) {
        this.hPosition = value;
    }

    /**
     * Gets the value of the vAlign property.
     * 
     * @return
     *     possible object is
     *     {@link VAlignType }
     *     
     */
    public VAlignType getVAlign() {
        return vAlign;
    }

    /**
     * Sets the value of the vAlign property.
     * 
     * @param value
     *     allowed object is
     *     {@link VAlignType }
     *     
     */
    public void setVAlign(VAlignType value) {
        this.vAlign = value;
    }

    /**
     * Gets the value of the vPosition property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getVPosition() {
        return vPosition;
    }

    /**
     * Sets the value of the vPosition property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setVPosition(BigDecimal value) {
        this.vPosition = value;
    }

}
