//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.29 at 02:22:12 PM CST 
//


package com.openfms.utils.dcp.subtitles;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>anyURI">
 *       &lt;attribute name="HAlign" type="{}hAlignType" />
 *       &lt;attribute name="HPosition" type="{}positionType" />
 *       &lt;attribute name="VAlign" type="{}vAlignType" />
 *       &lt;attribute name="VPosition" type="{}positionType" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "value"
})
@XmlRootElement(name = "Image")
public class Image {

    @XmlValue
    @XmlSchemaType(name = "anyURI")
    protected String value;
    @XmlAttribute(name = "HAlign")
    protected HAlignType hAlign;
    @XmlAttribute(name = "HPosition")
    protected BigDecimal hPosition;
    @XmlAttribute(name = "VAlign")
    protected VAlignType vAlign;
    @XmlAttribute(name = "VPosition")
    protected BigDecimal vPosition;

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the hAlign property.
     * 
     * @return
     *     possible object is
     *     {@link HAlignType }
     *     
     */
    public HAlignType getHAlign() {
        return hAlign;
    }

    /**
     * Sets the value of the hAlign property.
     * 
     * @param value
     *     allowed object is
     *     {@link HAlignType }
     *     
     */
    public void setHAlign(HAlignType value) {
        this.hAlign = value;
    }

    /**
     * Gets the value of the hPosition property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getHPosition() {
        return hPosition;
    }

    /**
     * Sets the value of the hPosition property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setHPosition(BigDecimal value) {
        this.hPosition = value;
    }

    /**
     * Gets the value of the vAlign property.
     * 
     * @return
     *     possible object is
     *     {@link VAlignType }
     *     
     */
    public VAlignType getVAlign() {
        return vAlign;
    }

    /**
     * Sets the value of the vAlign property.
     * 
     * @param value
     *     allowed object is
     *     {@link VAlignType }
     *     
     */
    public void setVAlign(VAlignType value) {
        this.vAlign = value;
    }

    /**
     * Gets the value of the vPosition property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getVPosition() {
        return vPosition;
    }

    /**
     * Sets the value of the vPosition property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setVPosition(BigDecimal value) {
        this.vPosition = value;
    }

}
