//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.18 at 10:22:27 PM CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.smpte-ra.org/schemas/429-9/2007/AM", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.openfms.utils.dcp.smpte.pkl;
