//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.18 at 10:12:23 PM CST 
//


package com.openfms.utils.dcp.interop.pkl;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ReelType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ReelType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Id" type="{http://www.digicine.com/PROTO-ASDCP-CPL-20040511#}UUID"/>
 *         &lt;element name="AnnotationText" type="{http://www.digicine.com/PROTO-ASDCP-CPL-20040511#}UserText" minOccurs="0"/>
 *         &lt;element name="AssetList">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="MainMarkers" type="{http://www.digicine.com/PROTO-ASDCP-CPL-20040511#}MarkerAssetType" minOccurs="0"/>
 *                   &lt;element name="MainPicture" type="{http://www.digicine.com/PROTO-ASDCP-CPL-20040511#}PictureTrackFileAssetType" minOccurs="0"/>
 *                   &lt;element name="MainSound" type="{http://www.digicine.com/PROTO-ASDCP-CPL-20040511#}SoundTrackFileAssetType" minOccurs="0"/>
 *                   &lt;element name="MainSubtitle" type="{http://www.digicine.com/PROTO-ASDCP-CPL-20040511#}SubtitleTrackFileAssetType" minOccurs="0"/>
 *                   &lt;element name="ProjectorData" type="{http://www.digicine.com/PROTO-ASDCP-CPL-20040511#}ProjectorDataAssetType" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;any namespace='##other' maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ReelType", namespace = "http://www.digicine.com/PROTO-ASDCP-CPL-20040511#", propOrder = {
    "id",
    "annotationText",
    "assetList"
})
public class ReelType {

    @XmlElement(name = "Id", required = true)
    protected String id;
    @XmlElement(name = "AnnotationText")
    protected UserText annotationText;
    @XmlElement(name = "AssetList", required = true)
    protected ReelType.AssetList assetList;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the annotationText property.
     * 
     * @return
     *     possible object is
     *     {@link UserText }
     *     
     */
    public UserText getAnnotationText() {
        return annotationText;
    }

    /**
     * Sets the value of the annotationText property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserText }
     *     
     */
    public void setAnnotationText(UserText value) {
        this.annotationText = value;
    }

    /**
     * Gets the value of the assetList property.
     * 
     * @return
     *     possible object is
     *     {@link ReelType.AssetList }
     *     
     */
    public ReelType.AssetList getAssetList() {
        return assetList;
    }

    /**
     * Sets the value of the assetList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReelType.AssetList }
     *     
     */
    public void setAssetList(ReelType.AssetList value) {
        this.assetList = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="MainMarkers" type="{http://www.digicine.com/PROTO-ASDCP-CPL-20040511#}MarkerAssetType" minOccurs="0"/>
     *         &lt;element name="MainPicture" type="{http://www.digicine.com/PROTO-ASDCP-CPL-20040511#}PictureTrackFileAssetType" minOccurs="0"/>
     *         &lt;element name="MainSound" type="{http://www.digicine.com/PROTO-ASDCP-CPL-20040511#}SoundTrackFileAssetType" minOccurs="0"/>
     *         &lt;element name="MainSubtitle" type="{http://www.digicine.com/PROTO-ASDCP-CPL-20040511#}SubtitleTrackFileAssetType" minOccurs="0"/>
     *         &lt;element name="ProjectorData" type="{http://www.digicine.com/PROTO-ASDCP-CPL-20040511#}ProjectorDataAssetType" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;any namespace='##other' maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "mainMarkers",
        "mainPicture",
        "mainSound",
        "mainSubtitle",
        "projectorData",
        "any"
    })
    public static class AssetList {

        @XmlElement(name = "MainMarkers", namespace = "http://www.digicine.com/PROTO-ASDCP-CPL-20040511#")
        protected MarkerAssetType mainMarkers;
        @XmlElement(name = "MainPicture", namespace = "http://www.digicine.com/PROTO-ASDCP-CPL-20040511#")
        protected PictureTrackFileAssetType mainPicture;
        @XmlElement(name = "MainSound", namespace = "http://www.digicine.com/PROTO-ASDCP-CPL-20040511#")
        protected SoundTrackFileAssetType mainSound;
        @XmlElement(name = "MainSubtitle", namespace = "http://www.digicine.com/PROTO-ASDCP-CPL-20040511#")
        protected SubtitleTrackFileAssetType mainSubtitle;
        @XmlElement(name = "ProjectorData", namespace = "http://www.digicine.com/PROTO-ASDCP-CPL-20040511#")
        protected List<ProjectorDataAssetType> projectorData;
        @XmlAnyElement(lax = true)
        protected List<Object> any;

        /**
         * Gets the value of the mainMarkers property.
         * 
         * @return
         *     possible object is
         *     {@link MarkerAssetType }
         *     
         */
        public MarkerAssetType getMainMarkers() {
            return mainMarkers;
        }

        /**
         * Sets the value of the mainMarkers property.
         * 
         * @param value
         *     allowed object is
         *     {@link MarkerAssetType }
         *     
         */
        public void setMainMarkers(MarkerAssetType value) {
            this.mainMarkers = value;
        }

        /**
         * Gets the value of the mainPicture property.
         * 
         * @return
         *     possible object is
         *     {@link PictureTrackFileAssetType }
         *     
         */
        public PictureTrackFileAssetType getMainPicture() {
            return mainPicture;
        }

        /**
         * Sets the value of the mainPicture property.
         * 
         * @param value
         *     allowed object is
         *     {@link PictureTrackFileAssetType }
         *     
         */
        public void setMainPicture(PictureTrackFileAssetType value) {
            this.mainPicture = value;
        }

        /**
         * Gets the value of the mainSound property.
         * 
         * @return
         *     possible object is
         *     {@link SoundTrackFileAssetType }
         *     
         */
        public SoundTrackFileAssetType getMainSound() {
            return mainSound;
        }

        /**
         * Sets the value of the mainSound property.
         * 
         * @param value
         *     allowed object is
         *     {@link SoundTrackFileAssetType }
         *     
         */
        public void setMainSound(SoundTrackFileAssetType value) {
            this.mainSound = value;
        }

        /**
         * Gets the value of the mainSubtitle property.
         * 
         * @return
         *     possible object is
         *     {@link SubtitleTrackFileAssetType }
         *     
         */
        public SubtitleTrackFileAssetType getMainSubtitle() {
            return mainSubtitle;
        }

        /**
         * Sets the value of the mainSubtitle property.
         * 
         * @param value
         *     allowed object is
         *     {@link SubtitleTrackFileAssetType }
         *     
         */
        public void setMainSubtitle(SubtitleTrackFileAssetType value) {
            this.mainSubtitle = value;
        }

        /**
         * Gets the value of the projectorData property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the projectorData property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getProjectorData().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ProjectorDataAssetType }
         * 
         * 
         */
        public List<ProjectorDataAssetType> getProjectorData() {
            if (projectorData == null) {
                projectorData = new ArrayList<ProjectorDataAssetType>();
            }
            return this.projectorData;
        }

        /**
         * Gets the value of the any property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the any property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAny().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Object }
         * 
         * 
         */
        public List<Object> getAny() {
            if (any == null) {
                any = new ArrayList<Object>();
            }
            return this.any;
        }

    }

}
