//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.13 at 06:19:47 AM CET 
//


package com.openfms.model.core.media.dcp.interop.am;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TrackFileAssetType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TrackFileAssetType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.digicine.com/PROTO-ASDCP-CPL-20040511#}GenericAssetType">
 *       &lt;sequence>
 *         &lt;element name="KeyId" type="{http://www.digicine.com/PROTO-ASDCP-CPL-20040511#}UUID" minOccurs="0"/>
 *         &lt;element name="Hash" type="{http://www.w3.org/2001/XMLSchema}base64Binary" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TrackFileAssetType", namespace = "http://www.digicine.com/PROTO-ASDCP-CPL-20040511#", propOrder = {
    "keyId",
    "hash"
})
@XmlSeeAlso({
    SubtitleTrackFileAssetType.class,
    PictureTrackFileAssetType.class,
    SoundTrackFileAssetType.class
})
public abstract class TrackFileAssetType
    extends GenericAssetType
{

    @XmlElement(name = "KeyId")
    protected String keyId;
    @XmlElement(name = "Hash")
    protected byte[] hash;

    /**
     * Gets the value of the keyId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKeyId() {
        return keyId;
    }

    /**
     * Sets the value of the keyId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKeyId(String value) {
        this.keyId = value;
    }

    /**
     * Gets the value of the hash property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getHash() {
        return hash;
    }

    /**
     * Sets the value of the hash property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setHash(byte[] value) {
        this.hash = value;
    }

}
